-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS ai_med."Aktualnie przyjmowane leki"
(
    id integer NOT NULL DEFAULT nextval('ai_med."Aktualnie przyjmowane leki_id_seq"'::regclass),
    atorvastatin_calcium__cholesterol boolean,
    ventolin__asthma boolean,
    hydrochlorothiazide__wysokie_cisnienie_krwi boolean,
    CONSTRAINT "Aktualnie przyjmowane leki_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med."Nazwa pliku z notatkami lekarskimi"
(
    lekarz_rodzinny character varying(100) COLLATE pg_catalog."default" NOT NULL,
    radiolog character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pacjentid integer NOT NULL DEFAULT nextval('ai_med."Nazwa pliku z notatkami lekarskimi_pacjentid_seq"'::regclass),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_pkey" PRIMARY KEY (lekarz_rodzinny, radiolog, pacjentid),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_lekarz_rodzinny_key" UNIQUE (lekarz_rodzinny),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_radiolog_key" UNIQUE (radiolog)
);

CREATE TABLE IF NOT EXISTS ai_med."Pacjent_Aktualnie przyjmowane leki"
(
    pacjentid integer NOT NULL DEFAULT nextval('ai_med."Pacjent_Aktualnie przyjmowane leki_pacjentid_seq"'::regclass),
    "Aktualnie przyjmowane lekiID" integer NOT NULL DEFAULT nextval('ai_med."Pacjent_Aktualnie przyjmowane _Aktualnie przyjmowane lekiID_seq"'::regclass),
    CONSTRAINT "Pacjent_Aktualnie przyjmowane leki_pkey" PRIMARY KEY (pacjentid, "Aktualnie przyjmowane lekiID")
);

CREATE TABLE IF NOT EXISTS ai_med."Pacjent_leczenie_w_kierunku_kod_ICD-10"
(
    pacjentid integer NOT NULL DEFAULT nextval('ai_med."Pacjent_leczenie_w_kierunku_kod_ICD-10_pacjentid_seq"'::regclass),
    "leczenie_w_kierunku_kod_ICD-10ID" integer NOT NULL DEFAULT nextval('ai_med."Pacjent_leczenie_w_kierunku_k_leczenie_w_kierunku_kod_ICD-1_seq"'::regclass),
    CONSTRAINT "Pacjent_leczenie_w_kierunku_kod_ICD-10_pkey" PRIMARY KEY (pacjentid, "leczenie_w_kierunku_kod_ICD-10ID")
);

CREATE TABLE IF NOT EXISTS ai_med."leczenie_w_kierunku_kod_ICD-10"
(
    id integer NOT NULL DEFAULT nextval('ai_med."leczenie_w_kierunku_kod_ICD-10_id_seq"'::regclass),
    u07 boolean,
    i10 boolean,
    j45 boolean,
    r51 boolean,
    g43 boolean,
    CONSTRAINT "leczenie_w_kierunku_kod_ICD-10_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.morfologia
(
    id integer NOT NULL DEFAULT nextval('ai_med.morfologia_id_seq'::regclass),
    ilosc_erytrocytow real,
    stezenie_hemoglobiny real,
    mcv real,
    mch real,
    mchc real,
    rdw real,
    pacjentid integer NOT NULL DEFAULT nextval('ai_med.morfologia_pacjentid_seq'::regclass),
    CONSTRAINT morfologia_pkey PRIMARY KEY (id, pacjentid),
    CONSTRAINT morfologia_id_key UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS ai_med.objawy
(
    id integer NOT NULL DEFAULT nextval('ai_med.objawy_id_seq'::regclass),
    bol_glowy boolean NOT NULL,
    zmeczenie boolean NOT NULL,
    CONSTRAINT objawy_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.obrazy
(
    id integer NOT NULL DEFAULT nextval('ai_med.obrazy_id_seq'::regclass),
    radiologiczne boolean,
    histopatologiczne boolean,
    pacjentid integer NOT NULL DEFAULT nextval('ai_med.obrazy_pacjentid_seq'::regclass),
    CONSTRAINT obrazy_pkey PRIMARY KEY (id, pacjentid),
    CONSTRAINT obrazy_id_key UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS ai_med.operacje
(
    id integer NOT NULL DEFAULT nextval('ai_med.operacje_id_seq'::regclass),
    data_przeszczepu_serca date,
    data_wyciecia_migdalkow date,
    CONSTRAINT operacje_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.pacjent
(
    id integer NOT NULL DEFAULT nextval('ai_med.pacjent_id_seq'::regclass),
    imie character varying(57) COLLATE pg_catalog."default" NOT NULL,
    nazwisko character varying(57) COLLATE pg_catalog."default" NOT NULL,
    wiek date NOT NULL,
    CONSTRAINT pacjent_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.pacjent_objawy
(
    pacjentid integer NOT NULL DEFAULT nextval('ai_med.pacjent_objawy_pacjentid_seq'::regclass),
    objawyid integer NOT NULL DEFAULT nextval('ai_med.pacjent_objawy_objawyid_seq'::regclass),
    CONSTRAINT pacjent_objawy_pkey PRIMARY KEY (pacjentid, objawyid)
);

CREATE TABLE IF NOT EXISTS ai_med.pacjent_operacje
(
    pacjentid integer NOT NULL DEFAULT nextval('ai_med.pacjent_operacje_pacjentid_seq'::regclass),
    operacjeid integer NOT NULL DEFAULT nextval('ai_med.pacjent_operacje_operacjeid_seq'::regclass),
    CONSTRAINT pacjent_operacje_pkey PRIMARY KEY (pacjentid, operacjeid)
);

ALTER TABLE IF EXISTS ai_med."Nazwa pliku z notatkami lekarskimi"
    ADD CONSTRAINT "FKNazwa plik780425" FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med."Pacjent_Aktualnie przyjmowane leki"
    ADD CONSTRAINT fkpacjent_ak498623 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med."Pacjent_Aktualnie przyjmowane leki"
    ADD CONSTRAINT fkpacjent_ak968980 FOREIGN KEY ("Aktualnie przyjmowane lekiID")
    REFERENCES ai_med."Aktualnie przyjmowane leki" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med."Pacjent_leczenie_w_kierunku_kod_ICD-10"
    ADD CONSTRAINT fkpacjent_le349503 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med."Pacjent_leczenie_w_kierunku_kod_ICD-10"
    ADD CONSTRAINT fkpacjent_le368073 FOREIGN KEY ("leczenie_w_kierunku_kod_ICD-10ID")
    REFERENCES ai_med."leczenie_w_kierunku_kod_ICD-10" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.morfologia
    ADD CONSTRAINT fkmorfologia741262 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.obrazy
    ADD CONSTRAINT fkobrazy350846 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.pacjent_objawy
    ADD CONSTRAINT fkpacjent_ob595829 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.pacjent_objawy
    ADD CONSTRAINT fkpacjent_ob779371 FOREIGN KEY (objawyid)
    REFERENCES ai_med.objawy (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.pacjent_operacje
    ADD CONSTRAINT fkpacjent_op11149 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.pacjent_operacje
    ADD CONSTRAINT fkpacjent_op831575 FOREIGN KEY (operacjeid)
    REFERENCES ai_med.operacje (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;