-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS ai_med."Przyjmowane leki"
(
    id integer NOT NULL DEFAULT nextval('ai_med."Aktualnie przyjmowane leki_id_seq"'::regclass),
    atorvastatin_calcium__cholesterol boolean,
    ventolin__asthma boolean,
    hydrochlorothiazide__wysokie_cisnienie_krwi boolean,
    data_przymowania date,
    CONSTRAINT "Aktualnie przyjmowane leki_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med."Nazwa pliku z notatkami lekarskimi"
(
    lekarz_rodzinny character varying(100) COLLATE pg_catalog."default" NOT NULL,
    radiolog character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pacjentid serial NOT NULL DEFAULT nextval('ai_med."Nazwa pliku z notatkami lekarskimi_pacjentid_seq"'::regclass),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_pkey" PRIMARY KEY (lekarz_rodzinny, radiolog, pacjentid),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_lekarz_rodzinny_key" UNIQUE (lekarz_rodzinny),
    CONSTRAINT "Nazwa pliku z notatkami lekarskimi_radiolog_key" UNIQUE (radiolog)
);

CREATE TABLE IF NOT EXISTS ai_med."leczenie_w_kierunku_kod_ICD_10"
(
    id serial NOT NULL DEFAULT nextval('ai_med."leczenie_w_kierunku_kod_ICD-10_id_seq"'::regclass),
    data_rozpoczecia_leczenia_u07 date,
    data_rozpoczecia_leczenia_i10 date,
    data_rozpoczecia_leczenia_j45 date,
    data_zakonczenia_leczenia_u07 date,
    data_zakonczenia_leczenia_i10 date,
    data_zakonczenia_leczenia_j45 date,
    CONSTRAINT "leczenie_w_kierunku_kod_ICD_10_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.morfologia
(
    id serial NOT NULL DEFAULT nextval('ai_med.morfologia_id_seq'::regclass),
    ilosc_erytrocytow real,
    stezenie_hemoglobiny real,
    mcv real,
    mch real,
    mchc real,
    rdw real,
    pacjentid serial NOT NULL DEFAULT nextval('ai_med.morfologia_pacjentid_seq'::regclass),
    data_wykonanej_morfologii date,
    CONSTRAINT morfologia_pkey PRIMARY KEY (id, pacjentid),
    CONSTRAINT morfologia_id_key UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS ai_med.objawy
(
    id serial NOT NULL DEFAULT nextval('ai_med.objawy_id_seq'::regclass),
    bol_glowy boolean,
    zmeczenie boolean,
    data_obserwowanych_objawow date,
    CONSTRAINT objawy_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.obrazy
(
    id serial NOT NULL DEFAULT nextval('ai_med.obrazy_id_seq'::regclass),
    radiologiczne character varying(100),
    histopatologiczne character varying(100),
    pacjentid serial NOT NULL DEFAULT nextval('ai_med.obrazy_pacjentid_seq'::regclass),
    CONSTRAINT obrazy_pkey PRIMARY KEY (id, pacjentid),
    CONSTRAINT obrazy_id_key UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS ai_med.operacje
(
    id serial NOT NULL DEFAULT nextval('ai_med.operacje_id_seq'::regclass),
    data_przeszczepu_serca date,
    data_wyciecia_migdalkow date,
    CONSTRAINT operacje_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ai_med.pacjent
(
    id serial NOT NULL DEFAULT nextval('ai_med.pacjent_id_seq'::regclass),
    imie character varying(57) COLLATE pg_catalog."default" NOT NULL,
    nazwisko character varying(57) COLLATE pg_catalog."default" NOT NULL,
    data_urodzenia date NOT NULL,
    CONSTRAINT pacjent_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS ai_med."Przyjmowane leki"
    ADD FOREIGN KEY (id)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ai_med."Nazwa pliku z notatkami lekarskimi"
    ADD CONSTRAINT "FKNazwa plik780425" FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med."leczenie_w_kierunku_kod_ICD_10"
    ADD FOREIGN KEY (id)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ai_med.morfologia
    ADD CONSTRAINT fkmorfologia741262 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.objawy
    ADD FOREIGN KEY (id)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS ai_med.obrazy
    ADD CONSTRAINT fkobrazy350846 FOREIGN KEY (pacjentid)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS ai_med.operacje
    ADD FOREIGN KEY (id)
    REFERENCES ai_med.pacjent (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;